server:
  port: 8092

  spring:
    datasource:
      username: sa
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
