server:
  port: 8090

  spring:
    application:
      name: orquestrador

  management:
    health:
      diskspace:
        enabled: false
    endpoint:
      prometheus:
        show-details: always
      metrics:
        enabled: true
    endpoints:
      web:
        exposure:
          include: '*'

  info:
    app:
      name: @project.name@
